### ISSUE TITLE
Diacritical marks are ignored when differientiating

### ISSUE THREAD

**Issue by hadithmv** [wickedest/Mergely#169]
While mergely does not by default ignore things like whitespace, case and accents, it does however ignore diacritical marks.

I've included a picture as well as a diff file that shows this for a couple of languages:

![image](https://user-images.githubusercontent.com/30223914/193479341-0ec7a17e-9e11-4fec-8a00-0c59365b7872.png)
[RL2vASt1.zip](https://github.com/wickedest/Mergely/files/9693722/RL2vASt1.zip)

**Comment by hadithmv** [comment]
It seems I can only download a single diff file from the site, yet import requires two separate files for two different sides. So instead here's a link: https://editor.mergely.com/UsHJyREC/

**Comment by hadithmv** [comment]
Or because merge left/right arrows are there, it does know that there are differences, just doesn't visually show them with colors as expected.

**Comment by wickedest** [comment]
@hadithmv, thanks for reporting the issue. there are actually 2 separate diffs being run.  The 1st is by line, and only detects lines that are different.  The 2nd is by character, within the line.  It appears the 2nd diff may be failing diacritical marks for some reason.

**Comment by hadithmv** [comment]
Its been a while, and I don't know if this would be of help, but,

![image](https://github.com/wickedest/Mergely/assets/30223914/678e4464-463f-487f-b4fa-ced7650b2a9c)

This is how vscode's shows it on their diff compare, it highlights the exact place where the change occurs. I thought that since it was open source, it might be possible to check out how are getting this to work.

**Comment by hadithmv** [comment]
here's how another diff compare tool fixed this particular issue:

https://gitlab.gnome.org/GNOME/meld/-/commit/d272016a481a9f9563d318a79ce9767cb8ad69ef

might be of help.

**Comment by wickedest** [comment]
Sorry - this has been on the bottom of the pile for a while.

This is a tough one. Normally, diacriticals can be combined into a single character, e.g. `a` + `´` = `á`. This can be done with [String.normalize("NFC")](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#parameters), but normalize does not work in this case.

For example, if we look at `كلمة` and `كَلمة`:

![image](https://github.com/wickedest/Mergely/assets/871639/e8ee3763-be52-479b-9195-0a2efba43908)

I am not a unicode expert, so I'm a bit lost because while it behaves like a diacritical, as far as I can tell, `\u064E` is something else. I understand diacriticals to be in these ranges ([source](https://en.wikipedia.org/wiki/Combining_character)):

* 0300-036F
* 1AB0-1AFF
* 1DC0-1DFF
* 20D0-20FF
* 2DE2-2DFF
* FE20-FE2F

[\u064E](https://www.compart.com/en/unicode/U+064E) is not in those ranges and is identified as an "Arabic Fatha". Unlike [\u0300](https://www.compart.com/en/unicode/U+0300) _is_ a "Diacritical".

My _guess_ is that the Fatha cannot be combined into a single character using normalize and whenever Mergely encounters these Fatha's, then it should include the adjacent character in the diff (i.e. `['0643', '064E']`). But that isn't going to be easy. For starters, outside of the ranges above, I have no idea how many unicode characters behave this way.

**Comment by wickedest** [comment]
The problem seems to be specifically with [nonspacing marks](https://www.compart.com/en/unicode/category/Mn). The diacritical might only be a subset.

**Comment by hadithmv** [comment]
Checked out the fix

It doesn't seem to be applied on the main page: https://www.mergely.com

It does work on the editor page though: https://editor.mergely.com

However, when I try using the cdn files of the latest release, it doesnt seem applied to them either:
https://jsbin.com/nedozegegu/edit?html,css,output
